local opt = vim.opt

vim.cmd("inoremap jh <Esc>")
vim.cmd("set expandtab")
vim.cmd("set textwidth=120")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set autoindent")
vim.cmd("set ruler")
vim.cmd("syntax on")
vim.cmd("set showcmd")
vim.cmd("set clipboard=unnamed")
vim.cmd("set number")
vim.cmd("set relativenumber")
